/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      colors: {
        m3: {
          primary: '#006874',
          'on-primary': '#ffffff',
          'primary-container': '#97f0ff',
          'on-primary-container': '#001f24',
          secondary: '#4a6267',
          'on-secondary': '#ffffff',
          'secondary-container': '#cde7ec',
          'on-secondary-container': '#051f23',
          tertiary: '#525e7d',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#dae2ff',
          'on-tertiary-container': '#0e1b37',
          surface: '#f8fafa',
          'surface-dim': '#d8dada',
          'surface-bright': '#f8fafa',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f2f4f4',
          'surface-container': '#eceeee',
          'surface-container-high': '#e6e8e8',
          'surface-container-highest': '#e1e3e3',
          'on-surface': '#191c1d',
          'on-surface-variant': '#3f484a',
          outline: '#6f797a',
          'outline-variant': '#bfc8ca',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#410002',
          // Dark theme overrides
          'dark-primary': '#4fd8eb',
          'dark-on-primary': '#00363d',
          'dark-primary-container': '#004f58',
          'dark-on-primary-container': '#97f0ff',
          'dark-secondary': '#b1cbd0',
          'dark-on-secondary': '#1c3438',
          'dark-secondary-container': '#334b4f',
          'dark-surface': '#191c1d',
          'dark-surface-container': '#1d2021',
          'dark-surface-container-high': '#282a2b',
          'dark-surface-container-highest': '#333536',
          'dark-on-surface': '#e1e3e3',
          'dark-on-surface-variant': '#bfc8ca',
          'dark-outline': '#899294',
        },
      },
      borderRadius: {
        'xs': '4px',
        'm3': '12px',
        'm3-lg': '16px',
        'm3-xl': '28px',
      },
      boxShadow: {
        'm3-1': '0 1px 2px 0 rgba(0,0,0,0.3), 0 1px 3px 1px rgba(0,0,0,0.15)',
        'm3-2': '0 1px 2px 0 rgba(0,0,0,0.3), 0 2px 6px 2px rgba(0,0,0,0.15)',
        'm3-3': '0 4px 8px 3px rgba(0,0,0,0.15), 0 1px 3px 0 rgba(0,0,0,0.3)',
      },
    },
  },
  plugins: [],
}
