/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      colors: {
        m3: {
          primary: '#064E3B',
          'on-primary': '#ffffff',
          'primary-container': '#A7F3D0',
          'on-primary-container': '#022C22',
          // Primary tonal palette for gradient backgrounds
          'primary-10': '#022C22',
          'primary-20': '#064E3B',
          'primary-30': '#065F46',
          'primary-50': '#059669',
          secondary: '#92400E',
          'on-secondary': '#ffffff',
          'secondary-container': '#FEF3C7',
          'on-secondary-container': '#451A03',
          // Secondary tonal palette for gradient backgrounds
          'secondary-10': '#451A03',
          'secondary-20': '#78350F',
          'secondary-30': '#92400E',
          tertiary: '#57534E',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#E7E5E4',
          'on-tertiary-container': '#1C1917',
          // Tertiary tonal palette for gradient backgrounds
          'tertiary-10': '#1C1917',
          'tertiary-20': '#292524',
          'tertiary-30': '#44403C',
          surface: '#F9FAFB',
          'surface-dim': '#D1D5DB',
          'surface-bright': '#F9FAFB',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#F3F4F6',
          'surface-container': '#ECEEEF',
          'surface-container-high': '#E5E7EB',
          'surface-container-highest': '#DFE1E4',
          'on-surface': '#111827',
          'on-surface-variant': '#374151',
          outline: '#6B7280',
          'outline-variant': '#D1D5DB',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#410002',
          // Dark theme overrides
          'dark-primary': '#6EE7B7',
          'dark-on-primary': '#022C22',
          'dark-primary-container': '#064E3B',
          'dark-on-primary-container': '#A7F3D0',
          'dark-secondary': '#FCD34D',
          'dark-on-secondary': '#451A03',
          'dark-secondary-container': '#78350F',
          'dark-surface': '#111827',
          'dark-surface-container': '#1F2937',
          'dark-surface-container-high': '#374151',
          'dark-surface-container-highest': '#4B5563',
          'dark-on-surface': '#F3F4F6',
          'dark-on-surface-variant': '#D1D5DB',
          'dark-outline': '#9CA3AF',
        },
      },
      borderRadius: {
        'xs': '4px',
        'm3': '12px',
        'm3-lg': '16px',
        'm3-xl': '28px',
      },
      boxShadow: {
        'm3-1': '0 1px 2px 0 rgba(0,0,0,0.3), 0 1px 3px 1px rgba(0,0,0,0.15)',
        'm3-2': '0 1px 2px 0 rgba(0,0,0,0.3), 0 2px 6px 2px rgba(0,0,0,0.15)',
        'm3-3': '0 4px 8px 3px rgba(0,0,0,0.15), 0 1px 3px 0 rgba(0,0,0,0.3)',
      },
    },
  },
  plugins: [],
}
